version : "3"
services:
  music-eruka-server:
    image: eurekaservice-app
    build: Music-Eruka-Server/
    restart: always
    network_mode: host
    container_name: eureka-server-docker
    ports:
      - "8761:8761"
    expose:
      - 8761

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo
    network_mode: host

  config-server:
    image: config-server
    build: config-server
    restart: always
    network_mode: host
    container_name: config-server
    ports:
      - "8888:8888"
    expose:
      - 8888

  track-service:
    image: track-service
    build: Track-Service
    restart: always
    network_mode: host
    container_name: track-service
    depends_on:
      - mongo
      - config-server
    ports:
      - "8083:8083"
    expose:
      - 8083

  user-service:
    image: userservice
    build: userservice
    restart: always
    network_mode: host
    container_name: user-service
    depends_on:
      - mongo
      - config-server
    ports:
      - "8085:8085"
    expose:
      - 8085

  zuulgatewayproxy:
    image: zuulgatewayproxy
    build: zuulgatewayproxy
    restart: always
    network_mode: host
    container_name: zuulgatewayproxy
    ports:
      - "8800:8800"
    expose:
      - 8800