spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_SERVER_URL:https://github.com/himacp/server-configuration.git}

server:
  port: 8099

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
fetch-registry: true
register-with-eureka: true